### ISSUE TITLE
Specific roles can assign specific roles

### ISSUE THREAD

**Issue by danieljaffe** [uclaacm/ACM-at-UCLA-Discord-Bot#16]
Ideally, a Committee President would have a command that they can run to add or remove the role of committee officer (for their respective committee) to someone in the server. This reduces mod overhead and allows each Cprez to be more self sufficient and independent in their committee management

Pseudo code:
    if (role == "cprez" && role == "hack officer"):
        allow role assignment of "hack officer" && "officer"

This would need to be done through the bot and hopefully could be simplified to a single toggle command:
    !officer

The command would assign and remove the general "officer" role as well as the one that corresponds to the command issuer's committee

**Comment by changyang-liu** [comment]
Comments from meeting:
- 2 different commands for add and remove
- commands for intern as well
- automatic assign committee based on president's committee

**Comment by changyang-liu** [comment]
done
