### ISSUE TITLE
Verify external students emails

### ISSUE THREAD

**Issue by danieljaffe** [uclaacm/ACM-at-UCLA-Discord-Bot#23]
We want to allow any email address ending in .edu to be allows to get verified, though with a different tag. Since they are not a UCLA student they will have restricted server access. This should at least cover US schools. I'm at a loss for how to cover international universities but if you think of something, comment and maybe we can incorporate that too.

Let me know when this is in progress and I'll create a tag to use for these individuals since we won't want to use the "Verified" one we have been using.

**Comment by entrohpy** [comment]
Will use "Guest" role in place of "Verified" role
