### ISSUE TITLE
Unhandled Missing Permissions API error

### ISSUE THREAD

**Issue by entrohpy** [uclaacm/ACM-at-UCLA-Discord-Bot#47]
May return Missing Permissions error from API when the bot attempts to verify/perform any action on a user with a higher role. Must handle appropriately.

Currently, as we're running the bot under pm2, the bot does not go offline.

**Comment by Tristan816la** [comment]
Hey my name is Tristan and I'm an intern for the dev team. could I get more background on this issue?

**Comment by entrohpy** [comment]
Hey Tristan! Welcome to ACM and glad to have you on board :). So on Discord, users cannot modify properties of users with higher roles. Since the bot is also technically a user with a bot-specific role, the same rules apply. 
<img width="714" alt="Screen Shot 2021-11-30 at 13 15 22" src="https://user-images.githubusercontent.com/12547595/144130047-b9841e21-1101-4ef1-8420-97a57b2e68ac.png">

On our server, the bot's role is lower than the Admin and PVP role and thus it cannot perform any operations on users with those roles. So if an Admin or PVP tried to verify/rename themselves et cetera, the bot would return a Missing Permissions Error. 

This also crashes the bot however we have it running under `pm2`, a node process manager which automatically restarts the bot in case of a crash.

Unfortunately, there's really no way for Admins or PVP to do anything with the bot (on themselves) so the best solution is just to catch the thrown error and have the bot reply with a clean error message.

This is a non-critical issue since PVP and Admin are small and static (at least for a year) but it would be nice for the bot to catch all unhandled errors.

**Comment by Tristan816la** [comment]
Hey Rohit, thanks for all this info! I understand the issue now. So instead of increasing the role of the bot, we want to just have a nicer error message to let admins and pvp know about this issue. I could work on it ASAP if that's the case. In the meantime, I notice I need a .env file to set up the environment. Do you know who I could reach out to for that? Thank you!

**Comment by advaithg** [comment]
>  I notice I need a .env file to set up the environment. Do you know who I could reach out to for that? Thank you!

I can send you this information!

**Comment by entrohpy** [comment]
Great, thanks @advaithg. Sorry for the late reply @Tristan816la. I was distracted by something for all of yesterday (-_-;)

**Comment by Tristan816la** [comment]
These might be a series of dumb questions, but I was wondering:

1. After using `npm run dev` and having a discord bot logged in, where could I talk to that bot? 
![image](https://user-images.githubusercontent.com/52658897/148131371-563cf860-2e49-4aa0-a2f6-1edb5f157ca6.png)
2. Also, is there a way for me to simulate the behavior for an Admin or PVP when calling `verify`?
3. Is the roles page @entrohpy you sent from the Discord Developer Console? Do I need access to that to resolve this issue?

**Comment by advaithg** [comment]
For 1 and 2, will send you a link to access the bot!
Will leave @entrohpy to respond to 3, since I'm not sure what you got sent

**Comment by entrohpy** [comment]
> 3. Is the roles page @entrohpy you sent from the Discord Developer Console? Do I need access to that to resolve this issue?
@Tristan816la, it's from Server Settings > Roles (accessible from discord itself) but you may not have access to this. However, I don't think you will need it!
