### ISSUE TITLE
Split command functions into separate files

### ISSUE THREAD

**Issue by entrohpy** [uclaacm/ACM-at-UCLA-Discord-Bot#8]
make codebase more maintainable and readable by splitting command functions into separate files

**Comment by danieljaffe** [comment]
Hah! I'm glad you made this issue. This was literally going to be my next request since it's starting to get pretty long.  :)

**Comment by Bwoltz** [comment]
Alright, I'm finally gonna take a shot at this. I think it will give me a chance to get familiar with the codebase. Give me the weekend to try it out.

**Comment by entrohpy** [comment]
Hi Brett, thanks for taking this up. Let me know if there's anything you're confused about because I admit there are barely any comments. Reachable on Github, Discord or Messenger.
